name: ui_simple_calendar
description: "A simple Flutter package for displaying a calendar. Advanced customize"
version: 0.0.2
homepage: https://github.com/phuongvudev/ui_simple_calendar

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.20.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true